#!/usr/bin/env python3
"""Generate a topic index from chapter headings and terminology registry."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from collections import OrderedDict

ROOT = pathlib.Path(__file__).resolve().parents[1]
TERMS = ROOT / "book/registries/terminology.yml"
CHAPTERS = ROOT / "book/chapters"
OUTPUT = ROOT / "book/INDEX.md"
HEADING = re.compile(r"^(#{1,3})\s+(.+?)\s*$")


def norm(text: str) -> str:
    return re.sub(r"\s+", " ", text.strip().strip("`"))


def read_terms() -> list[dict[str, str]]:
    if not TERMS.exists():
        return []

    terms: list[dict[str, str]] = []
    current: dict[str, str] | None = None
    in_terms = False
    for raw in TERMS.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if line.strip() == "terms:":
            in_terms = True
            continue
        if not in_terms:
            continue
        match = re.match(r"^\s{2}([A-Za-z0-9_]+):\s*$", line)
        if match:
            if current:
                terms.append(current)
            current = {"key": match.group(1)}
            continue
        match = re.match(r"^\s{4}([a-z_]+):\s*(.*)\s*$", line)
        if match and current is not None:
            value = match.group(2).strip()
            if value.startswith(("'", '"')) and value.endswith(("'", '"')) and len(value) >= 2:
                value = value[1:-1]
            current[match.group(1)] = value
    if current:
        terms.append(current)
    return terms


def chapter_paths() -> list[pathlib.Path]:
    return sorted(p for p in CHAPTERS.glob("[0-9][0-9]-*.md") if not p.name.endswith("-brief.md"))


def chapter_title(path: pathlib.Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return norm(line[2:])
    return path.stem


def parse_headings(path: pathlib.Path) -> list[str]:
    headings: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = HEADING.match(line)
        if match and match.group(1) in {"##", "###"}:
            headings.append(norm(match.group(2)))
    return headings


def build_index() -> str:
    chapters = chapter_paths()
    chapter_info = [(path, chapter_title(path), parse_headings(path)) for path in chapters]

    topic_map: OrderedDict[str, list[tuple[int, str]]] = OrderedDict()
    for path, _, headings in chapter_info:
        chapter_num = int(path.name[:2])
        for heading in headings:
            topic_map.setdefault(heading, [])
            if (chapter_num, path.stem) not in topic_map[heading]:
                topic_map[heading].append((chapter_num, path.stem))

    term_map: OrderedDict[str, dict[str, str]] = OrderedDict()
    for entry in read_terms():
        preferred = norm(entry.get("preferred", entry["key"]))
        term_map[preferred] = {
            "definition": norm(entry.get("definition", "")),
            "first_defined": entry.get("first_defined", ""),
        }

    lines = [
        "# Index",
        "",
        "Generated by `scripts/generate_index.py`. This is a topic index keyed to the current markdown chapters and terminology registry.",
        "It uses chapter links instead of page numbers because pagination is not yet part of the production workflow.",
        "Do not edit manually.",
        "",
        "## Chapter Map",
        "",
    ]
    for path, title, _ in chapter_info:
        chapter_num = int(path.name[:2])
        lines.append(f"- [Chapter {chapter_num}: {title}](chapters/{path.name})")
    lines.append("")

    lines += ["## Core Terms", ""]
    for term in sorted(term_map, key=str.lower):
        entry = term_map[term]
        definition = entry["definition"]
        if definition and definition[-1] not in ".!?":
            definition = f"{definition}."
        first_defined = entry["first_defined"]
        chapter_ref = f"[Chapter {int(first_defined[:2])}](chapters/{first_defined}.md)" if first_defined else ""
        if definition and chapter_ref:
            lines.append(f"- `{term}` — {definition} First defined in {chapter_ref}.")
        elif definition:
            lines.append(f"- `{term}` — {definition}")
        elif chapter_ref:
            lines.append(f"- `{term}` — First defined in {chapter_ref}.")
    lines.append("")

    lines += ["## Topic Index", ""]
    for topic in sorted(topic_map, key=str.lower):
        refs = topic_map[topic]
        links = ", ".join(f"[Chapter {num}](chapters/{stem}.md)" for num, stem in refs)
        lines.append(f"- `{topic}` — {links}")
    lines += [
        "",
        "## Generation Summary",
        "",
        f"- Chapters scanned: {len(chapter_info)}",
        f"- Core terms: {len(term_map)}",
        f"- Topic entries: {len(topic_map)}",
        "",
        "Owner: Publishing Pipeline  ",
        "Purpose: Generate a navigation-oriented index from chapter headings and core terms  ",
        "Evidence grade: A for structure; derived from the current manuscript and terminology registry  ",
        "Assumptions: Chapter numbering stays stable and pagination will be added later if a print index is needed  ",
        "Open questions: Whether the eventual print edition should replace chapter links with page numbers  ",
        "Handoff: Principal author / layout editor",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    output = build_index()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != output:
            print("FAIL: book/INDEX.md is missing or stale", file=sys.stderr)
            return 1
        print("PASS: INDEX.md is current")
        return 0

    OUTPUT.write_text(output, encoding="utf-8")
    print("WROTE: book/INDEX.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
