#!/usr/bin/env python3
"""Generate a chapter source map and deduplicated bibliography."""
from __future__ import annotations
import argparse, pathlib, re, sys
from collections import OrderedDict

ROOT = pathlib.Path(__file__).resolve().parents[1]
CARDS = ROOT / "book/evidence/source-ledger"
CHAPTERS = ROOT / "book/chapters"
OUTPUT = ROOT / "book/REFERENCES.md"
CITE = re.compile(r"\[CITE:\s*([^]]+)\]")
FIELD = re.compile(r"^([^:\n]+):\s*(.*?)\s*$", re.M)

def norm(s: str) -> str:
    return re.sub(r"\s+", " ", s.strip().strip("`"))

def read_cards() -> dict[str, dict[str, str]]:
    result = {}
    for path in sorted(CARDS.glob("*.md")):
        fields = {norm(k).lower(): norm(v) for k, v in FIELD.findall(path.read_text(encoding="utf-8"))}
        sid = fields.get("source id", path.stem)
        location = fields.get("file path / url") or fields.get("file path") or fields.get("url") or ""
        card = {"id": sid, "title": fields.get("title", ""), "author": fields.get("author/issuer", ""),
                "date": fields.get("date", ""), "type": fields.get("source type", "source"),
                "location": location, "grade": fields.get("evidence grade", "")}
        if not card["title"] or not card["grade"]:
            raise ValueError(f"incomplete source card: {path.relative_to(ROOT)}")
        if sid in result:
            raise ValueError(f"duplicate Source ID: {sid}")
        result[sid] = card
    return result

def chapter_paths():
    return sorted(p for p in CHAPTERS.glob("[0-9][0-9]-*.md") if not p.name.endswith("-brief.md"))

def cited(path: pathlib.Path) -> list[str]:
    slugs = []
    for marker in CITE.findall(path.read_text(encoding="utf-8")):
        slugs.extend(s.strip() for s in marker.split(";") if s.strip())
    return list(dict.fromkeys(slugs))

def render(cards):
    chapters, order, missing = OrderedDict(), [], []
    for path in chapter_paths():
        chapters[path.stem] = cited(path)
        for slug in chapters[path.stem]:
            if slug not in cards: missing.append(f"{path.name}: {slug}")
            elif slug not in order: order.append(slug)
    if missing: raise ValueError("missing source cards:\n" + "\n".join(missing))
    works = OrderedDict()
    for slug in order:
        c = cards[slug]
        key = tuple(norm(c[k]).lower() for k in ("title", "author", "date", "location"))
        works.setdefault(key, []).append(slug)
    number = {slug: i for i, slugs in enumerate(works.values(), 1) for slug in slugs}
    lines = ["# References", "", "Generated by `scripts/generate_references.py`. Do not edit manually.", "",
             "Source-card citations are resolved first, then cards describing the same work are deduplicated.", "",
             "## Chapter Source Map", ""]
    for chapter, slugs in chapters.items():
        nums = list(dict.fromkeys(number[s] for s in slugs))
        lines += [f"### `{chapter}`", "", ", ".join(f"[{n}](#ref-{n})" for n in nums), ""]
    lines += ["## Bibliography", ""]
    for i, slugs in enumerate(works.values(), 1):
        c = cards[slugs[0]]
        identity = ". ".join(x for x in (c["author"], c["date"], f'*{c["title"]}*') if x)
        loc = f"[source]({c['location']})" if c["location"].startswith(("http://", "https://")) else f"`{c['location']}`" if c["location"] else "Location not recorded"
        lines += [f'<a id="ref-{i}"></a>', f"{i}. {identity}. {c['type']}. {loc}",
                  f"   Source cards: {', '.join(f'`{s}`' for s in slugs)}. Evidence grade: {c['grade']}.", ""]
    lines += ["## Generation Summary", "", f"- Unique cited source cards: {len(order)}",
              f"- Deduplicated cited works: {len(works)}", f"- Unused source cards: {len(set(cards)-set(order))}", "",
              "Owner: Reference Pipeline  ", "Purpose: Generate chapter source maps and a deduplicated bibliography  ",
              "Evidence grade: Inherited from source cards  ",
              "Assumptions: Identical normalized title, author, date, and location identify one work  ",
              "Open questions: Final publisher citation style and incomplete lecture metadata  ",
              "Handoff: Principal author / copyeditor", ""]
    return "\n".join(lines)

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--check", action="store_true"); args = ap.parse_args()
    try: output = render(read_cards())
    except ValueError as exc: print(exc, file=sys.stderr); return 1
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != output:
            print("FAIL: book/REFERENCES.md is missing or stale", file=sys.stderr); return 1
        print("PASS: citations resolve and REFERENCES.md is current"); return 0
    OUTPUT.write_text(output, encoding="utf-8"); print("WROTE: book/REFERENCES.md"); return 0

if __name__ == "__main__": raise SystemExit(main())
